dist: trusty
language: java
jdk: openjdk8
sudo: required

addons:
  apt:
    sources:
    - heroku

env:
  global:

services:
- docker

install: true

script:
- docker-compose build
- ci_env=`bash <(curl -s https://codecov.io/env)`
- docker-compose run $ci_env unit_test
- docker-compose run $ci_env integration_test
- docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
- docker tag studentscollab registry.heroku.com/studentscollab/web
- docker push registry.heroku.com/studentscollab/web
- heroku container:release web -a studentscollab
