dist: trusty

language: java

jdk: openjdk8
# ou bien
# jdk: oraclejdk8
# jdk: oraclejdk9

install: mvn dependency:go-offline
# MIEUX QUE
# install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
# ou que
# install: true

script:
- mvn test -B -V
- bash <(curl -s https://codecov.io/bash) -c -F unit
- mvn clean verify -Dskip.surefire.tests=true -B -V
- bash <(curl -s https://codecov.io/bash) -c -F integration