language: java

jdk: openjdk8

dist: trusty

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

install: mvn dependency:go-offline
         mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn clean verify